apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Don't override namespace - resources define their own

resources:
  - ../base

namePrefix: staging-

labels:
  - pairs:
      environment: staging
    includeSelectors: false

images:
  - name: ghcr.io/schlagenkraft/web/ski-website
    newTag: simple

replicas:
  - name: ski-website
    count: 2

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ski-website
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: ski-website
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: ski-website