apiVersion: v1
kind: Service
metadata:
  name: external-dns-metrics-ski-dev
  # FIX: Service must be in the same namespace as the Deployment
  namespace: external-dns
spec:
  selector:
    # This label must match the labels on your pod template
    app: external-dns-ski-dev
  ports:
    - name: http-metrics
      protocol: TCP
      port: 7979
      targetPort: 7979