apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ski-website
  namespace: ski-website
  annotations:
    cert-manager.io/cluster-issuer: "carverauto-issuer"
    metallb.universe.tf/allow-shared-ip: "true"
    metallb.universe.tf/address-pool: k3s-pool
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ski.example.com
    secretName: ski-website-tls
  rules:
  - host: ski.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ski-website
            port:
              number: 80