apiVersion: v1
kind: Service
metadata:
  name: ski-website
  namespace: ski-website
  labels:
    app: ski-website
spec:
  type: ClusterIP
  selector:
    app: ski-website
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP